server.port=8083

# Lưu ý: Cấu hình dưới đây trỏ vào localhost vì bạn đang chạy Redis local. 
# Nếu triển khai thật, đổi localhost thành 192.168.2.2 như kiến trúc gốc.
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.application.name=order-service
